/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.product.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Products service. Represents a row in the &quot;SP_Products&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.product.service.model.impl.ProductsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.product.service.model.impl.ProductsImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Products
 * @generated
 */
@ProviderType
public interface ProductsModel
	extends BaseModel<Products>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a products model instance should use the {@link Products} interface instead.
	 */

	/**
	 * Returns the primary key of this products.
	 *
	 * @return the primary key of this products
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this products.
	 *
	 * @param primaryKey the primary key of this products
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this products.
	 *
	 * @return the uuid of this products
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this products.
	 *
	 * @param uuid the uuid of this products
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the products ID of this products.
	 *
	 * @return the products ID of this products
	 */
	public long getProductsId();

	/**
	 * Sets the products ID of this products.
	 *
	 * @param productsId the products ID of this products
	 */
	public void setProductsId(long productsId);

	/**
	 * Returns the service name of this products.
	 *
	 * @return the service name of this products
	 */
	@AutoEscape
	public String getServiceName();

	/**
	 * Sets the service name of this products.
	 *
	 * @param serviceName the service name of this products
	 */
	public void setServiceName(String serviceName);

	/**
	 * Returns the service des of this products.
	 *
	 * @return the service des of this products
	 */
	@AutoEscape
	public String getServiceDes();

	/**
	 * Sets the service des of this products.
	 *
	 * @param serviceDes the service des of this products
	 */
	public void setServiceDes(String serviceDes);

	/**
	 * Returns the service price of this products.
	 *
	 * @return the service price of this products
	 */
	@AutoEscape
	public String getServicePrice();

	/**
	 * Sets the service price of this products.
	 *
	 * @param servicePrice the service price of this products
	 */
	public void setServicePrice(String servicePrice);

	/**
	 * Returns the group ID of this products.
	 *
	 * @return the group ID of this products
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this products.
	 *
	 * @param groupId the group ID of this products
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this products.
	 *
	 * @return the company ID of this products
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this products.
	 *
	 * @param companyId the company ID of this products
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this products.
	 *
	 * @return the user ID of this products
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this products.
	 *
	 * @param userId the user ID of this products
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this products.
	 *
	 * @return the user uuid of this products
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this products.
	 *
	 * @param userUuid the user uuid of this products
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this products.
	 *
	 * @return the user name of this products
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this products.
	 *
	 * @param userName the user name of this products
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this products.
	 *
	 * @return the create date of this products
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this products.
	 *
	 * @param createDate the create date of this products
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this products.
	 *
	 * @return the modified date of this products
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this products.
	 *
	 * @param modifiedDate the modified date of this products
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	@Override
	public Products cloneWithOriginalValues();

}